### ISSUE TITLE
Better documentation

### ISSUE THREAD

**Issue by mxstbr** [mxstbr/react-boilerplate#14]
- [x] **Files**
- [x] **Explanation of the possible `npm` commands**
- [x] Testing
    - [x] **How to write unit tests**
        - [x] **Mocha**
        - [x] **expect**
        - [x] **Real world usage**
            - [x] **Reducers**
            - [x] **`rewire`**
            - [x] **Actions**
    - [ ] *How to write good unit tests* (see [this article](https://medium.com/javascript-scene/what-every-unit-test-needs-f6cd34d9836d) and [this response](https://medium.com/@bruderstein/fancy-assertion-libraries-a40d7a45ceb0) for inspo)
    - [x] **How to write component tests**
        - [x] **Shallow rendering**
        - [x] **enzyme**
    - [x] **Browser testing**
        - [x] **`npm run serve`**
- [ ] Explanation of the main design decisions behind this boilerplate (maybe incomplete)
    - [ ] User side
        - [ ] JS
            - [ ] ESNext Features (see #165)
            - [x] **ImmutableJS**
            - [x] React
                - [ ] react-router
                - [x] **Components/Containers split** (see #33, [this article](http://jamesknelson.com/should-i-use-react-createclass-es6-classes-or-stateless-functional-components/))
                - [x] **Redux**
                    - [x] **reselect** (see #61)
                    - [ ] redux-simple-router
                    - [x] **redux-saga**
            - [ ] eslint
                - [ ] Airbnb style
            - [ ] *FontFaceObserver*
        - [x] CSS
            - [x] **CSS Modules**
            - [x] sanitize.css
            - [x] **PostCSS**
                - [x] **cssnext**
                - [x] **autoprefixer**
                - [x] postcss-focus
                - [x] cssnano
        - [x] **Offline First**
            - [x] **ServiceWorker**
            - [x] **AppCache**
    - [x] **Developer side**
        - [ ] Webpack
        - [ ] Babel
        - [x] **Beginner**
            - [ ] Modules (`export` and `import`)
            - [x] **Prerequisites**
                - [x] **node**
                    - [x] *npm*
                - [x] **git**
- [x] **FAQs**
    - [x] **nodejs-legacy for linux** (see [here](http://plaidzooks.tumblr.com/post/36894116867/using-nodejs-on-debianubuntu-systems))
    - [ ] **`Error: listen EADDRINUSE 127.0.0.1:3000`**
    - [ ] Hot-reloading doesn't work?
    - [x] Why do I need this?
    - [x] Can I use Sass with this?
    - [ ] I don't want to use Redux!
- [x] **Gotchas**
    - [x] **Images in the HTML file** (Copy and past from README)
- [ ] Advanced Patterns
    - [ ] Ducks (see #27)
    - [ ] ryanflorences non-flat app structure (see #27)
- [ ] *Deployment guides*
  - [ ] *scp*
  - [ ] *Heroku*
  - [ ] *Codeship*
  - [ ] *Beanstalk*

Legend: *`Cursive todos`* are nice-to-haves, but only to be done when everything else is done, and **`bold todos`** are must-haves before releasing

> Note: If you're planning on writing one of these sections, please be sure to talk about the `v3.0.0` branch and to submit your PR against the `v3.0.0` branch!

**Comment by swastik** [comment]
ember-cli has a great user guide for some reference: http://ember-cli.com/user-guide/

**Comment by mxstbr** [comment]
An uncomplete list of design decisions/modules we use that need guides/documentation/explanations as to why and how we chose and use them.

# User side

- [ ] ES6
- [ ] React
- [ ] Redux
- [ ] redux-thunk
- [ ] react-router
- [ ] FontFaceObserver

----

- [ ] PostCSS
- [ ] postcss-focus
- [ ] postcss-import
- [ ] postcss-simple-vars
- [ ] autoprefixer

----

- [ ] eslint
- [ ] AirBnB coding style

----

- [ ] Mocha
- [ ] expect

# Developer side

- [ ] Why/how webpack?
- [ ] Why/how babel?

**Comment by mxstbr** [comment]
Add `PREREQUISITES.md` for complete beginners, which explains/links to guide that explain how to install and use node, npm, git,...

**Comment by mxstbr** [comment]
Add documentation on how to write good unit tests, and improve current unit tests to reflect that. See [this article](https://medium.com/javascript-scene/what-every-unit-test-needs-f6cd34d9836d) and [this response](https://medium.com/@bruderstein/fancy-assertion-libraries-a40d7a45ceb0)

**Comment by mxstbr** [comment]
Advanced Patterns:

- [ ] reselect (see #61)

**Comment by mxstbr** [comment]
Add documentation on how to write component tests

**Comment by mxstbr** [comment]
More documentation inspo: https://github.com/coryhouse/react-slingshot

**Comment by mxstbr** [comment]
Nice webpack how-to for beginners by @petehunt: 

https://github.com/petehunt/webpack-howto/blob/master/README.md

**Comment by mxstbr** [comment]
Document protected master branch. (See #72)

**Comment by mxstbr** [comment]
More documentation inspo: https://github.com/davezuko/react-redux-starter-kit

**Comment by mxstbr** [comment]
Amazing documentation for beginners by @lewiscowper https://github.com/lewiscowper/visualising-npm which we're [allowed to steal](https://twitter.com/LewisCowper/status/693109794857705472)

**Comment by mxstbr** [comment]
Design decisions inspiration: https://github.com/reactuate/reactuate

**Comment by mxstbr** [comment]
I'll close this issue as most of this points are touched upon, and will open specific issues for points we still need to touch.

**Comment by CHRISTOPHERDIEHL** [comment]
A beanstalk/ AWS or Docker deployment guide would be very helpful.
